### ISSUE TITLE
Add some background to actually see black transparent svgs/pngs

### ISSUE THREAD

**Issue by simonschaufi** [Flowpack/media-ui#127]
### Description

Showing transparent svgs/pngs with black text are not visible

#### Actual behavior

- Upload the typo3 png

![typo3-1200px-transparent](https://user-images.githubusercontent.com/941794/160019509-ddb8c6ff-1fd9-406f-9d00-2bf27ff9cf20.png)

- Click on it to show the modal window
- Only the orange logo is visible but not the TYPO3 text

#### Expected

I would like to see some background like in gimp

![image](https://user-images.githubusercontent.com/941794/160019763-0fdf0507-e825-4937-a243-3d46d2d93b1f.png)

This exists actually already in the inspector but not in the media module:

![image](https://user-images.githubusercontent.com/941794/160162828-bcbb3c67-a04c-4088-b3bd-aa96a52d5722.png)

So use the same background pattern also in the full media module like in the inspector and you are done ;)

**Comment by Sebobo** [comment]
Good idea, thx
