### ISSUE TITLE
Show unused assets

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#13]
F.e. To help with cleaning up old assets.

See the initial feature request https://github.com/neos/neos-development-collection/issues/2354

**Comment by DrillSergeant** [comment]
Our customer just gave me the ok to sponsor 1700 EUR for this feature :-). Import is, that he can filter those assets.

**Comment by Sebobo** [comment]
Thx!

We already had many discussions about how to implement this feature without performance issues.
I think we can prioritise this feature with your help and create a first async usage calculation which can be used in the UI.
Probably a JobQueue will be involved and needs to be run by a cron job.

**Comment by Sebobo** [comment]
@DrillSergeant this feature is now fully integrated since 0.4.0 (and fixed a bug in 0.4.1).
Check https://github.com/Flowpack/media-ui#fast-asset-usage-calculation--unused-assets-view for details how to use it.
