### ISSUE TITLE
A way to filter Assets without Collection

### ISSUE THREAD

**Issue by paavo** [Flowpack/media-ui#143]
Similar to the "Untagged" Option i'd love to have an "Assets without Collection" Filter to detect all assets without a collection. 

As discussed in Slack with @Sebobo

**Comment by Sebobo** [comment]
Just got it working in the #184 branch with a modified NeosAssetProxyRepository.
Will use this for some more features now.

**Comment by paavo** [comment]
Thats awesome, thanks @Sebobo 🙏

**Comment by Sebobo** [comment]
Resolved in #184
