### ISSUE TITLE
BUG: Thumbnail overflows container in MediaSelectionScreen

### ISSUE THREAD

**Issue by grebaldi** [Flowpack/media-ui#147]
![Screenshot_2022-11-04_11-34-39](https://user-images.githubusercontent.com/2522299/199956894-f1d15712-7cf9-42d3-a2fc-f231da322095.png)

### Description

The thumbnail image representing media items in the `MediaSelectionScreen` overflows its container. This happens only in the `MediaSelectionScreen` when called from the Inspector in the Neos Content Module. It also appears only to happen on certain screen resolutions.

### Steps to Reproduce

I'm not sure if this is limited to specific image resolutions. If not, the issue should be reproducible by just opening the `MediaSelectionScreen`.

#### Expected behavior

The thumbnail image representing media items in the `MediaSelectionScreen` does not overflow its container.

#### Actual behavior

![Screenshot_2022-11-04_11-35-21](https://user-images.githubusercontent.com/2522299/199958461-c831338d-081c-41fd-b55c-1d4b5b6b800e.png)

Responsive Behavior:

https://user-images.githubusercontent.com/2522299/199958517-caf18007-8e82-4b30-8531-ca14e9047069.mp4

### Affected Versions

Neos: 8.1.2

UI: 8.1.1

Media Module: master

**Comment by markusguenther** [comment]
Can verify this issue and will check out
![Uploading Screenshot 2022-11-10 at 15.34.55.png…]()
 the fix later, try to fix the e2e as well :)

**Comment by Sebobo** [comment]
I'm a bit confused if this was a regression as I always tested with various shaped of images

**Comment by markusguenther** [comment]
In the module it works, but some CSS is different in the selector/browser, and therefore it is broken.
No one blames you ;)
