### ISSUE TITLE
Tags do not work as intended

### ISSUE THREAD

**Issue by healthyplus-yves** [Flowpack/media-ui#159]
Procedure:

Open new media management

Create new tag

Assign tag to document

Select tag 

→ Not all documents with the selected tag are displayed, tags and defined documents are not updated

Expected behaviour:

Tag is assigned to document

When the tag is selected, only the documents containing the tag are displayed.

All documents with the selected tag are displayed.

After manually reloading the page, the behaviour is correct. However, this is not easy for the user to understand.

**Comment by Sebobo** [comment]
Thx, this can probably be easily fixed and sounds like a caching issue. Will check.

**Comment by Sebobo** [comment]
Hm interesting. This only seems to happen if you click on the tag which is inside a collection. 
It doesn't happen when you click on the same tag inside `all`.

Can you confirm that?

**Comment by healthyplus-yves** [comment]
Ok, yes i can confirm that behaviour.
So this is rather a feature than a bug. :-)

**Comment by Sebobo** [comment]
Yes, but I understand the UX issue which was maybe not as apparent in the old module, even if it had the same behavior.

**Comment by Sebobo** [comment]
I adjusted the collection in #162 

<img width="248" alt="Bildschirm­foto 2022-12-06 um 16 00 16" src="https://user-images.githubusercontent.com/596967/205947449-af5b738d-9464-45bb-9a2e-57b5eb97ab3c.png">
