### ISSUE TITLE
FEATURE monitoring of purchased asset expiration

### ISSUE THREAD

**Issue by tdausner** [Flowpack/media-ui#169]
### Description

For management of purchased assets the IPTC ApplicationRecord tags 37 + 38 (ExpirationDate + ExpirationTime) should be monitored on asset delivery.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

Monitoring of IPTC ApplicationRecord tags 37 + 38 (ExpirationDate + ExpirationTime)

- on expiration the asset is not delivered. Instead a dummy asset is delivered.
- on expiration an email is generated. Recipients (and message) are `yaml` configured
- the mentioned IPTC tags are editable, if not set

#### Actual behavior

No asset expiration monitoring

### Affected Versions

Neos: *

UI: *

Media Module: *

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by Sebobo** [comment]
Thanks for the topic. I don't see this in the UI package as it related more to the media API and core functionality/extensibility. 
The editable IPTC metadata is covered by #98 which you can comment with the specific requirements/fields.

Therefore I would move the issue to Neos itself if this is fine for you?

**Comment by tdausner** [comment]
You're right concerning the functionality - it's not UI related. Please move to Neos.
I'll comment on #98 concerning IPTC editing.

**Comment by Sebobo** [comment]
Seems I cannot move the issue, would you copy the text and open it in the Neos development collection?

**Comment by tdausner** [comment]
done. see [flow-development-collection#2954](https://github.com/neos/flow-development-collection/issues/2954)
