### ISSUE TITLE
Localise all labels at least for English and German

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#175]
All(?) labels are currently being inserted with a translate call. But there are almost no corresponding entries in the XLF files.

We should have all labels in English and German for the version 1.0.0 and also keep in mind to have a crowd sourced translation soon after.

- [ ] Create separate XLF files for each package
- [ ] Adjust translation methods to work with different packages
- [ ] Translate everything

**Comment by Sebobo** [comment]
I'm thinking that it would be best to have an individual XLF file for each JS feature/package. This should make it easier to work on specific parts and see quicker if something is missing.

**Comment by crydotsnake** [comment]
> Create separate XLF files for each package

What exactly do you mean with package? You mean those?:
https://github.com/Flowpack/media-ui/tree/main/Resources/Private/JavaScript

**Comment by Sebobo** [comment]
Yes
