### ISSUE TITLE
Update build setup

### ISSUE THREAD

**Issue by mhsdesign** [Flowpack/media-ui#178]
we currently have no support for optional chaining and thus no way to import the new react-components ;)

```
$ parcel build src/index.tsx --public-url . --out-dir ../../../Public/Assets -o main.bundle.js
🚨  Flowpack.Media.Ui/node_modules/@neos-project/react-ui-components/lib-esm/_chunk/7LKEAFDV.js: Unexpected token: punc (.)

# const wrapperBoundingBox = props.wrapperRef.current?.getBoundingClientRect();
#                                                    |____________________________here
```

also parcel requires me indirectly to have `g++` installed LOL

**Comment by Sebobo** [comment]
I've now upgraded to Parcel v2 and the latest Neos extensibility in #184 

Which part did you try to build?

**Comment by mhsdesign** [comment]
I imagine for the media ui backend? But nice that you’re taking care ^^

**Comment by Sebobo** [comment]
Done in #184
