### ISSUE TITLE
[Folders] Implement API & Schema for reading and modifying folders

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#180]
- [x] GraphQL resolver
- [ ] DTOs
- [ ] Interface (extensibility!)
- [ ] Dummy implementation

Relates: #64

**Comment by tdausner** [comment]
@Sebobo can you please define the the GraphQL part so I could map it to my implementation?

**Comment by Sebobo** [comment]
Not planned for now, as we use hierarchical collections in #184.
