### ISSUE TITLE
[Folders] Content Repository backend folder source

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#181]
- [ ] Create CR Adaptor
- [ ] Configurable rootpath
- [ ] Nodetypes

Relates: #64

**Comment by tdausner** [comment]
see https://github.com/tdausner/Neos.Folder

**Comment by tdausner** [comment]
@Sebobo can be obsoleted if [you define the the GraphQL part so I could map it to my implementation (#180)](#180).

**Comment by Sebobo** [comment]
Hi @tdausner, I don't want to have an external dependency for this feature, the t3n/graphql dependency is already a problem that needs a replacement (which I don't have the resources for). That's why I would prefer a simple implementation in this package for now and more flexibility via extensibility.

**Comment by Sebobo** [comment]
Paused for now

**Comment by Sebobo** [comment]
Not planned for now, as we use hierarchical collections in #184.
