### ISSUE TITLE
BUG: tag selection for asset does not consider chosen collection

### ISSUE THREAD

**Issue by batabana** [Flowpack/media-ui#187]
### Description

After assigning a collection to an asset, I still get **all** tags in the tag selection dropdown instead of just the ones associated to the collection. I can select tags from other collections, leading to technically invalid tag assignments.

### Steps to Reproduce

1. Create collections with corresponding tags
2. Select an asset, select a collection for it
3. Open the tag selection

#### Expected behavior

Should only offer tags related to the chosen collection(s)

#### Actual behavior

The asset belongs to collection "Radsport", so the tag dropdown should only offer tag "Downhill-Event", instead it offers all available tags.

![grafik](https://user-images.githubusercontent.com/36864084/233065388-8dd3e9cf-4ecc-4c01-800f-0a5525546ecb.png)

**Comment by batabana** [comment]
Mhm okay i see. I was assuming the "old way" would still be the basic functionality in the new media module.

The use case for the customer: They have different sections that act rather autonomously. And a lot of picture "galleries" from different events in different sections. The idea was to use collections for the sections, tags for the events and nest them accordingly. The events usually have rather unspecific names though - so it will be hard for them to choose from the long list of tags if they are not filtered by section. And the rest of our implementation kind of depends on the tags being correctly set according to the collection they are in. Also it is very unlikely that a collection for an asset has to be changed, but I understand that this is specfic to their use case. Actually a more folder based option to upload and manage pictures would be even better for their usecase, that's why we tried to find an equally easy workflow with the collection- and tags-concept.

**Comment by Sebobo** [comment]
Then you will be happy to know that folder feature related to https://github.com/Flowpack/media-ui/issues/64 will hopefully released in the next weeks. The folder feature is fully working, but I'm in the testing and polishing phase and also need a PR in the Neos core merged. That should solve a lot of use cases like the one you describe.

Additional sponsorship and help with the feature is of course very welcome.
