### ISSUE TITLE
BUG: Clicking on any existing image in the inspector results in never ending internal errors

### ISSUE THREAD

**Issue by tschoeki** [Flowpack/media-ui#197]
### Description

When logged into the Neos backend and clicking on an existing image in the inspector a neverending stream of internal errors pops up. This is true for any kind of image at neos.io (key visuals, image nodes, ...)

### Steps to Reproduce

1. Login to Neos.io via neos.io/neos
2. Select any image
3. Click on the image preview in the inspector on the right
4. See the errors appear on the top of the backend UI

#### Expected behavior

I expected to see no errors 😅 but more of a UI about the image enabling me to e.g. replace the image

#### Actual behavior

https://github.com/Flowpack/media-ui/assets/6280338/b0685f86-d6ed-48f8-a02b-25918d56b70b

[What actually happened]

### Affected Versions

Neos: 8.3.4

UI: 8.3.3

Media Module: 0.13.0-beta7

**Comment by ahaeslich** [comment]
This also happens if you click on the camera icon below the image. It will open up the media browser but will show no images. Just a never ending stream of internal error messages.

**Comment by Sebobo** [comment]
Fixed, migration was not executed after database was imported again.
