### ISSUE TITLE
Number of files in a collection should update automatically after upload.

### ISSUE THREAD

**Issue by crydotsnake** [Flowpack/media-ui#202]
### Description

Currently, when I upload new files to my collection, I have to reload the UI first to see how many files I have in my collection. But it would be cool if this would happen automatically with the upload, so I don't have to refresh the UI first, but see directly how many files I have in my collection.

![SCR-20230904-npux](https://github.com/Flowpack/media-ui/assets/39345336/633b9231-bd00-4a2a-9882-86b7ff578417)

### Affected Versions

Neos: 8.3

UI: 8.3

Media Module: 0.13.0-beta8

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by crydotsnake** [comment]
I noticed the same behavior also when i add a tag to a image. There i also have to reload the UI to see my image in the choosen tag.

**Comment by Sebobo** [comment]
Note for fixing this: trigger the ASSET_COUNT query in the mutation call, like done with other situations.

**Comment by Sebobo** [comment]
Quickly fixed it because I was in the code already for some other problem.
