### ISSUE TITLE
FEATURE: Allow search by tags like collections

### ISSUE THREAD

**Issue by crydotsnake** [Flowpack/media-ui#203]
### Description

Currently, it is not possible to search for the created tags via a search field, as is the case with Collections. Of course I can also simply search for my tag. But for the editor it would be more pleasant if there is a search field where I can search my newly created tag. Especially when I have more than 10 or 20 tags. The behavior should be similar to the Collections:

1. i have a search field in the tags field
2. with one click the list of tags pops up
    - I can either search them manually
    - Or I can use the search field to find my tag.

![SCR-20230905-igzb](https://github.com/Flowpack/media-ui/assets/39345336/62255891-897b-4e9e-b1e4-fab0c7057c20)

Please add your feedback, if you would find this feature useful! Or if you have any other opinions.

**Comment by soee** [comment]
+1

**Comment by soee** [comment]
Please see https://github.com/Flowpack/media-ui/pull/216
