### ISSUE TITLE
BUG: new media selector close button hovers view toggle button

### ISSUE THREAD

**Issue by soee** [Flowpack/media-ui#205]
### Description

When `media-ui` apckage is installed and we use the new media selector to pick assets from properties inspector, the inspector close button hovers toggle view button from the inspector interface.

### Steps to Reproduce

1. Install `media-ui` package
2. Make sure the new media selector is used
3. Open media selector from properties inspector

#### Expected behavior

All media selector interface elements should be fully visible/accessible.

#### Actual behavior

The toggle view button is hovered by the close inspector buton.

![image](https://github.com/Flowpack/media-ui/assets/1798417/d073eea2-7e5a-4bc1-b9c5-bd18b9f25ff9)

### Affected Versions

Neos: 8.2

UI: 

Media Module: 0.13.0

**Comment by Sebobo** [comment]
This worked before and broke at some point. Will fix.
