### ISSUE TITLE
UX: Confirmation for changing a collection's parent collection

### ISSUE THREAD

**Issue by lorenzulrich** [Flowpack/media-ui#207]
The "Collection" selector of an Asset is at the same place as the "Parent collection" selector of a collection.

Changing the collection of an Asset basically means moving a file, which is a minor action.

Changing the parent collection of an Asset Collection restructures the Collection tree which has more consequences.

As both elements are (rightfully) at the same place, you might easily mix it up after e.g. changing collection and accidentially change the parent collection of a collection.

Therefore, I would suggest a confirmation dialog for this action.

### Affected Versions

Neos: 8.3
UI: 8.3.4
Media Module: 0.13

**Comment by Sebobo** [comment]
I wanted to remove those selectors with #190 and replace all those with drag & drop or cut & paster buttons in the tree.
Just don't know when this is done, so we could add a dialog until then and even keep the dialog when it's done in the tree.
