### ISSUE TITLE
UX: Functionality of clipboard is unclear

### ISSUE THREAD

**Issue by lorenzulrich** [Flowpack/media-ui#209]
The term clipboard is normally used to copy or move "content" between "storages".

To me, it looks as if the Clipboard in the Media UI can only be used to delete multiple assets at once. While this is a valid use-case, I'm not sure it's an expected (sole) use-case for a Clipboard.

I would expect deleting multiple assets by multi-selection in the file list (which is also an established concept in Neos - see document and structure tree).

For the clipboard, I would imagine it could be used for moving many files at once.

Slightly related: I think that the "Flush clipboard" icon is not an intuitive choice:

![image](https://github.com/Flowpack/media-ui/assets/1816023/9338edcf-d518-466f-96f7-156c973e820c)

### Affected Versions

Neos: 8.3
UI: 8.3.4
Media Module: 0.13

**Comment by Sebobo** [comment]
The first use case for the clipboard was to prepare a list of assets which you want quick access to later in the media selection when working on content.

Then I added "delete" as first batch action and there is an open issue to add more actions like assign collections, tags, etc.

So you can browser through your media, collect assets and then work with them.

The multi-selection in the list has the disadvantage that you loose the selection when paginating. Though we also have an open issue for the batch actions in the list view. And also the drag&drop part is still not implemented and is an open issue.

**Comment by Sebobo** [comment]
I agree that the icon should be changed. Not sure yet which one would fit.

**Comment by Sebobo** [comment]
Already fixed in b93fa681fb7a2d8c2a262224cc405ebc0e7d5294
