### ISSUE TITLE
UX: Position of the upload button

### ISSUE THREAD

**Issue by lorenzulrich** [Flowpack/media-ui#210]
I'd like to discuss the position of the upload button:

![image](https://github.com/Flowpack/media-ui/assets/1816023/998f9502-9bd7-4c69-93ee-41b85d7e00d3)

It being above the "Collections" component and besides the list of assets makes it look like a "super-global" function, while at the same time the uploaded assets are added to the currently selected collection.

The position is the same in Google Drive, however the breadcrumb makes it clearer to me that I will upload it the currently selected folder:

![image](https://github.com/Flowpack/media-ui/assets/1816023/f170297e-d732-4608-ace7-a060de87734c)

In Dropbox, it is above the list of files which also makes it clearer to me:

![image](https://github.com/Flowpack/media-ui/assets/1816023/e71298d7-ed85-4fef-b168-8a06f60e9761)

I'm not saying I have the perfect solution here, but placing it like this would make more sense to me:

![image](https://github.com/Flowpack/media-ui/assets/1816023/c7bc9d8d-f9e8-4296-8b17-94b812ced6e3)

### Affected Versions

Neos: 8.3

UI: 8.3.4

Media Module: 0.13

**Comment by Sebobo** [comment]
I already tried a few things with a breadcrumb but couldn't find a good solution yet that doesn't steal too much screen space.
But I just thought about whether I could add the module breadcrumb to the existing breadcrumb at the top via a React portal. Would that be intuitive?

For now I would at least increase the size of the button. Sadly having it in the toolbar causes issues with smaller screens as there is more and more stuff.

**Comment by lorenzulrich** [comment]
@Sebobo I can well live with the current situation and the bigger button. Closing this.
