### ISSUE TITLE
AssetCollectionService_Original::getAssetCollectionAssetCount() must be of the type int, string returned

### ISSUE THREAD

**Issue by simonschaufi** [Flowpack/media-ui#215]
Exception in line 99 of .../Packages/Framework/Neos.Flow/Classes/ObjectManagement/DependencyInjection/DependencyProxy.php: Return value of Flowpack\Media\Ui\Service\AssetCollectionService_Original::getAssetCollectionAssetCount() must be of the type int, string returned

https://github.com/Flowpack/media-ui/blob/48a767e349f3f7202525668a7d3bd6f3328154e4/Classes/Service/AssetCollectionService.php#L56

this must be casted to int, then it works:

```php
$carry[$item['id']] = (int)$item['count'];
```

**Comment by Sebobo** [comment]
I don't unterstand, I never encountered this issue. How many collections do you have?

**Comment by simonschaufi** [comment]
Just a hand full. Maybe it depends on mysql?

I debugged at it returns a string as numer so "5" for example.

This is my mysql version: `mysql  Ver 8.0.34-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))`
