### ISSUE TITLE
Allow upload when picking item from the inspector

### ISSUE THREAD

**Issue by lorenzulrich** [Flowpack/media-ui#222]
If the Media UI is used to pick items from an inspector property, uploading assets should be (optionally - behind a feature flag) allowed.

**Comment by lorenzulrich** [comment]
BTW, I also think it is a good idea regarding consistency. Currently, you can delete an image in the dialog, but you cannot upload anything.

**Comment by Sebobo** [comment]
I think we can turn it on, test whether the layouts don't break and run with it. Uploading and immediately editing the asset in the dialog is probably better than any other current way.
