### ISSUE TITLE
Regression: Publish submenu button without padding

### ISSUE THREAD

**Issue by lorenzulrich** [Flowpack/media-ui#223]
The latest version of media-ui (0.14.2) introduced a regression that removes the left padding of the publish submenu button:

![image](https://github.com/Flowpack/media-ui/assets/1816023/7e36d2f7-cb78-4a23-b502-a30b5a9f52cf)

**Comment by Sebobo** [comment]
0.14.3 contains the hopefully correct bugfix this time
