### ISSUE TITLE
BUG: Usage urls are broken because of port rendered to url in docker setup

### ISSUE THREAD

**Issue by jannydiamond** [Flowpack/media-ui#234]
### Description

We have a docker compose setup for Neos where Neos is running on port 8081. On our staging and production environment we don't have a port in the url but the usage urls for images are generated with the server port where Neos is running. When clicking on such a link we get a broken page. When we remove the port from the Url the Usage link works correctly. It's also not a problem with the old Media modul.

### Steps to Reproduce

1. Running docker compose setup where Neos is running on a defined port in satging or production setup
2. Login into neos backend and go to new Media Ui
3. Click on "Show usages" for an image
4. Hover over image label and see url with port

#### Expected behavior

Port should not be rendered to usage url in staging an production context.

#### Actual behavior

![Screenshot 2024-03-26 at 11 07 24](https://github.com/Flowpack/media-ui/assets/8681488/c3d341a5-d8ef-454c-88c0-cece22b570ef)

Port is rendered to usage url in staging an production context.

### Affected Versions

Neos: 8.3.0

UI: 8.3.0

Media Module: 1.2.0

**Comment by kitsunet** [comment]
I assume the URLs are fine in the frontend?

**Comment by Sebobo** [comment]
@kitsunet I implemented a hack way to build the Uris for this view back then in \Flowpack\Media\Ui\Service\UsageDetailsService::buildNodeUri, but I don't know exactly why anymore. Quite possible there is a bug in there.
