### ISSUE TITLE
FEATURE: Let User sort Files by FileSize

### ISSUE THREAD

**Issue by paavo** [Flowpack/media-ui#236]
I'd love to sort files by File Size, to identify big files. 
Something like this would be nice:
![image](https://github.com/Flowpack/media-ui/assets/1118783/c3a06f99-d417-4a14-b888-8dcddf1de153)

**Comment by Sebobo** [comment]
This is possible since [0.13.0](https://github.com/Flowpack/media-ui/releases/tag/0.13.0)

**Comment by paavo** [comment]
> This is possible since [0.13.0](https://github.com/Flowpack/media-ui/releases/tag/0.13.0)

Oooops, look i was stuck on 0.12.x 🤦
