### ISSUE TITLE
BUG: Error by trying to delete assets which are still in use in the media browser

### ISSUE THREAD

**Issue by GuangHa** [Flowpack/media-ui#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you try to delete an asset which is still in use, you will get an internal error (500).

![image](https://github.com/user-attachments/assets/f0ddfaa2-ba12-4dab-bbfb-74b3c3ebe0e0)

### Expected Behavior

Another message, saying the asset is still in use and therefore unable to delete or maybe disable the delete function.

### Steps To Reproduce

1. Open media browser via Property-Editor
2. Try to delete an asset in use
3. Get Error

### Environment

```markdown
- Flow: 8.3.9
- Neos: 8.3.15
- PHP: 8.1.2
```

### Anything else?

It is now fixed in the Neos internal library, but occurs in the media ui package.
See https://github.com/neos/neos-development-collection/issues/5085

**Comment by Sebobo** [comment]
Can you check the exception that is created in this case and paste its content?
The problem might be unrelated to this package actually.

You should actually get the following error:
![CleanShot 2024-08-13 at 17 46 54](https://github.com/user-attachments/assets/af35f1a0-8b3e-46b7-9271-ac128c8cfbc4)

**Comment by Sebobo** [comment]
No feedback, closing the issue
