### ISSUE TITLE
It should be possible to have nested Tags

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/media-ui#3]

**Comment by Sebobo** [comment]
As discussed we can add this feature for Neos 5.2 and simply ignore it for the old UI.
Nesting tags would cause no conflict there.

**Comment by Sebobo** [comment]
Pushed this issue out of the alpha version target as the discussions with @bwaidelich and @dimaip brought up too many problems. We will first think about what we want long term and how we want to store them and then work on the implementation again. @bwaidelich will create another issue to discuss this architecture topic.

**Comment by Sebobo** [comment]
This will not be implemented as we want go introduce folders.
