### ISSUE TITLE
Large asset preview fails for files with special characters

### ISSUE THREAD

**Issue by bwaidelich** [Flowpack/media-ui#47]
### Steps to Reproduce

1. Install the [mediawiki](https://github.com/daniellienert/assetsource-mediawiki) asset source
2. Enter the new media module
3. click the expand button (labeled "preview Asset") on a file that contains special characters in its URL (for example: https://upload.wikimedia.org/wikipedia/de/0/0d/Umgebinde-Mezna_23_%282%29.JPG)

#### Expected behavior

The image is displayed in the preview modal

#### Actual behavior

The preview modal is empty

I assume it is due to some (missing) encoding here. The URL in the network panel seems correct and works when opened in a new browser tab

### Affected Versions

master (b7282b9)

**Comment by Sebobo** [comment]
Thanks for the report! 
From what I see the image is there but because of the super big size, the lightbox computes the transform incorrectly and the image is outside the lightbox. Will check if its a known bug of the lightbox library.

**Comment by Sebobo** [comment]
I created a patch. The lightbox lib seems to be unmaintained currently. 
Will have to decide how to proceed on that in a separate issue.

**Comment by bwaidelich** [comment]
Wow, that's what I call "quick reaction", thank you!
