### ISSUE TITLE
Inspector gets clipped

### ISSUE THREAD

**Issue by dimaip** [Flowpack/media-ui#51]
![image](https://user-images.githubusercontent.com/837032/97274600-ed6bb100-1845-11eb-8f3c-b57408a4e072.png)

**Comment by Sebobo** [comment]
I think I fixed this already in the `feature/edit-tags` branch.  Will check.

**Comment by Sebobo** [comment]
@dimaip this can be closed right?

**Comment by dimaip** [comment]
nope, still gets clipped for me
