### ISSUE TITLE
Unassigning collections from asset makes them reappear

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#56]
### Description

When a collection is assigned to an asset it works fine, but when it's being removed the response still contains the removed collection even though the asset was correctly updated in the database.
Seems to be somehow related on how the asset, the collection and the proxy are updated.

### Steps to Reproduce

See video

![AssetCollectionBugNewMediaUI 2020-10-29 09_48_45](https://user-images.githubusercontent.com/596967/97545911-f8e8e480-19cb-11eb-8ec5-b0ccd4ddab77.gif)

#### Expected behavior

The collection should not reappear.

#### Actual behavior

See video above. The collection reappears.

### Affected Versions

Media Module: current master

**Comment by grebaldi** [comment]
The bug lives here:
https://github.com/neos/neos-development-collection/blob/feb4bc74665691b321b21a4d59f825a7e9579c67/Neos.Media/Classes/Domain/Model/Asset.php#L459-L463

The method `setAssetCollections` of the Asset model in `Neos.Media` adds all existing asset collections to the newly assigned asset collection collection as a side effect. I'll try to figure out what's the intent behind these lines and will open an issue over at neos-development-collection.

**Comment by Sebobo** [comment]
Fixed with the next patch release for Neos 7.3+
