### ISSUE TITLE
Assets not compiled, uploadMaxFileSize for extra large files

### ISSUE THREAD

**Issue by snoblucha** [Flowpack/media-ui#63]
### Description

After compose update the UI stops working. After inspecting there were two issues with GraphQL. First is that we have to upload very large files (5GB)  but in GraphQL is defined Int. So it is over the limit and it ends up in error saying `Int cannot represent non 32-bit signed integer value`

```
"""
Configuration object containing helpful parameters for API interaction
"""
type Config {
    uploadMaxFileSize: Int
}
```

Second issue is, that in the commit https://github.com/Flowpack/media-ui/commit/f5990dc4b4f4e6c5ce7faa157fdf90e8aacef0a5 the GraphQL definition was changed, but the bundle was not build, so after the compose update ti will stop working with similar issue, `Unknown argument "tag" on field "assets" of type "Query". Did you mean "tagId` and on the UI it displays error. After yarn build it is ok, but it would be great to have it in the repository. 

### Steps to Reproduce

1. compose update
2. log in to backend
3. open the UI Media (new)

#### Expected behavior

Show UI of new Assets manager.

#### Actual behavior
![clipboard-202102162041-dvsgi](https://user-images.githubusercontent.com/265586/108127848-24dbc300-70ac-11eb-912f-dc09a94cadd3.png)

### Affected Versions

Neos: 7.0.0

UI: 7.0.x-dev aa2a198

Media Module: dev-master 520a508

**Comment by Sebobo** [comment]
Hi, thx for the issue!

I will push a new bundle today and adjust the limit. Didn't have 5GB files in my test environment 😉

**Comment by Sebobo** [comment]
Hi, you can now update to 0.2.0 which should resolve both issues.

Thx for testing. Feel free to open more issues or comment on existing ones if you find things that can be improved.
