### ISSUE TITLE
Check mediatype during media selection to prevent incorrect assignments

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#74]
F.e. Selecting a document for a node with a ImageInterface Property causes an exception

**Comment by KommunikativCh** [comment]
Hy, I try to implement in MediaSelectionScreen in RecoilRoot initialStates  to preset a Asset Filter (selectedMediaTypeState) 
 depending on type from MediaSelectionScreenProps. To show only images in ImageEditor Selection like in the old Media-Browser.

In Image Editor -> Image Selection type is "images"
in Asset Editor ->  Asset Selection type is ""

in new Media-Ui Asset Filter (selectedMediaTypeState) for Images is "image" and for Assets is ""

Shall we do this mapping from "images" => "image" and "" => "" in a constant, or somehow configurable in Settings frontendConfiguration.
Thanks for help.

**Comment by Sebobo** [comment]
Hi,

I think I would do the mapping inside the `MediaSelectionScreen` for now as its quite simple.

Setting the recoil state initially for the`selectedMediaTypeState` sounds reasonable. Probably another state would be helpful to make the typefilter disabled.

But we should also include the `mediaTypeConstraint` and `accept` options, but this could probably be done in a separate issue. Haven't looked into how they exactly work yet. And also why `mediaTypeConstraints` is ignored if `accept` is set.

**Comment by KommunikativCh** [comment]
OK Thanks

Yes I have implemented a new State for selectionAssetType to control the TypeFilter.

The mediaTypeConstraint and accept options, I will do with the issue #14.
