### ISSUE TITLE
Media Ui not loading

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/media-ui#78]
### Description

Every now and then the media UI is not loading.

Seems like the same error as in https://github.com/neos/redirecthandler-ui/issues/73

### Steps to Reproduce

Reload the media Ui

#### Actual behavior

![image](https://user-images.githubusercontent.com/642226/122722444-07914e00-d272-11eb-96af-302592321486.png)

### Affected Versions

Neos: 7.1

UI:

Media Module:

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by Sebobo** [comment]
@markusguenther we should probably fix that in 7.1 besides making the check in this package more robust. 
Maybe some more packages will also break.

**Comment by markusguenther** [comment]
So hopefully that is more sustainable now ;)
