### ISSUE TITLE
When creating collections or tags, success messages are rendered as errors.

### ISSUE THREAD

**Issue by grebaldi** [Flowpack/media-ui#83]
### Description

When creating collections or tags, success messages are rendered as errors:

https://user-images.githubusercontent.com/2522299/126901371-b732eeae-141d-4477-8121-bc1ac5977272.mp4

### Steps to Reproduce

1. Go the new Media Module
2. Create a new Collection or Tag

#### Expected behavior

A success message appears stating the success of the operation.

#### Actual behavior

An error message appears stating the success of the operation.

![Screenshot_2021-07-17_17-56-26](https://user-images.githubusercontent.com/2522299/126901420-6a39a26f-c66c-43b3-9b52-69af41149e28.png)

### Affected Versions

Neos: *
UI: *
Media Module: `master`

**Comment by Sebobo** [comment]
Not on my machine 🤔

In your screen I see you are in the creation dialog, maybe only there, because it uses a different notification API?

**Comment by grebaldi** [comment]
Good point, I'll check that.

**Comment by Sebobo** [comment]
Ah found the issue. I did some copy&paste quatsch in the selection screen
