### ISSUE TITLE
Tag named 'Header' breaks Media UI tag list 

### ISSUE THREAD

**Issue by pKallert** [Flowpack/media-ui#94]
### Description
I am not sure if this is a GraphQl Error or a Media UI Error, but it is an error and I think it is a very bad error. 
The GraphQL used in the MediaUI seems to try to call tag and collection names as functions and this makes the MediaUI angry. 
There is already a BugTicket in the t3n GraphQL Repository for that, see https://github.com/t3n/graphql/issues/35 
Perhaps the Media UI could somehow catch that and/or use a custom resolver? At least something that does not directly call a string as a function if the function exists. 
This is not strictly a MediaUI issue, but nothing is happening over at the GraphQL issue and this is breaking my Media UI Tags a lot. Also, this feels really bad.  

### Steps to Reproduce

1. Add a Tag named "Header" in the old MediaBrowser
2. Open the Flowpack Media UI

#### Expected behavior
The Tags are shown. 

#### Actual behavior
Tags are not shown and there is a JS Error [GraphQL error]: Message: Exception in line 33 of /application/Data/Temporary/Development/SubContextBeach/SubContextInstance/Cache/Code/Flow_Object_Classes/t3n_GraphQL_Service_DefaultFieldResolver.php: header() expects at most 3 parameters, 4 given - See also: xxx.txt, Location: [object Object], Path: tags 

### Affected Versions

Neos: 7.3

UI: 0.6.2

**Comment by Sebobo** [comment]
Thx for reporting. Will try to get in touch with Johannes to fix the underlying issue. Don't really want to built a workaround.

**Comment by Sebobo** [comment]
Hi @pKallert,

updating to the GraphQL lib https://github.com/t3n/graphql/releases/tag/3.0.2 should fix that. Can you verify?

**Comment by pKallert** [comment]
@Sebobo  works locally in my project 👍 
Should I update the composer file or should we leave it as it is?

**Comment by Sebobo** [comment]
I bumped the minimum version. Thx for the help.
