### ISSUE TITLE
Having nested tags breaks tag display & use

### ISSUE THREAD

**Issue by kdambekalns** [Flowpack/media-ui#95]
### Description

Having nested tags in the database breaks tag display and use.

### Steps to Reproduce

1. Create a tag that points to another tag as parent in the DB (needs to be done manually)
2. Reload the media UI – all tags disappear

#### Expected behavior

Either nested tags or a flat list of tags (as in the "old" media browser)

#### Actual behavior

No tags are shown

**Comment by kdambekalns** [comment]
Note: I know that is not officially supported in anyway, but I think it should either not break things, be implemented or https://github.com/neos/neos-development-collection/pull/2930 should be reverted again.

**Comment by Sebobo** [comment]
Yes we don't want to implement the nested tags as they create far more issues than they solve. Especially in the UI.

But we should fix this, correct.

**Comment by Sebobo** [comment]
Code was removed.
